# Generated by Django 3.0.3 on 2020-08-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('answer', models.TextField()),
                ('_question_type', models.CharField(choices=[('M', 'Multiple Selection'), ('S', 'Single Selection')], max_length=1)),
                ('explaination', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.Topic')),
            ],
        ),
    ]
