# Generated by Django 3.0.3 on 2020-08-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Topic',
        ),
    ]
