# Generated by Django 3.0.3 on 2020-09-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_auto_20200902_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(default='', upload_to='exam_app/'),
        ),
    ]
