# Generated by Django 3.0.3 on 2020-09-09 05:09

from django.db import migrations, models
import exam_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_question_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(default='', upload_to=exam_app.models.question_img_path),
        ),
    ]
